name: Build

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

env:
  BUILD_NAME: "1.0.${{ github.run_number }}"

jobs:
  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.base.repo.full_name != github.event.pull_request.head.repo.full_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: stable
          cache: true
          pub-cache: true

      - name: Cache Android SDK Components
        uses: actions/cache@v5
        with:
          path: |
            /usr/local/lib/android/sdk/ndk/27.0.12077973
            /usr/local/lib/android/sdk/cmake/3.22.1
          key: ${{ runner.os }}-android-sdk-${{ steps.flutter-action.outputs.VERSION }}-${{ hashFiles('**/build.gradle*', '**/app/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-android-sdk-

      - name: Setup Android signing key
        if: ${{ github.ref_name == 'main' }}
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_FILE_BASE64 }}" | base64 --decode > android/key.jks
          cat <<EOF > android/key.properties
          storePassword=${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword=${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyAlias=subspacerelay-play-upload
          storeFile=../key.jks
          EOF

      - name: Fetch dependencies
        run: flutter pub get
      
      - name: Check generated files are up to date
        run: |
          dart run build_runner build --delete-conflicting-outputs

          if [[ -n "$(git status --porcelain)" ]]; then
            git status --porcelain
            echo "::error title=Generated files out of date::Generated files are out of date"
            exit 1
          fi

      - name: Build
        run: |
          if [ '${{ github.ref_name }}' == 'main' ]; then
            flutter build appbundle --release --build-number="${{ github.run_number }}" --build-name="${{ env.BUILD_NAME }}"
          fi

          flutter build apk --debug --build-number="${{ github.run_number }}" --build-name="${{ env.BUILD_NAME }}"

      - name: Archive App Bundle
        uses: actions/upload-artifact@v7
        with:
          name: "subspace_relay_mobile_aab_release_v${{ env.BUILD_NAME }}"
          path: build/app/outputs/bundle/release/app-release.aab
          if-no-files-found: error

      - name: Archive APK
        uses: actions/upload-artifact@v7
        with:
          name: "subspace_relay_mobile_apk_debug_v${{ env.BUILD_NAME }}"
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error

      - name: Authenticate to GCP
        if: ${{ github.ref_name == 'main' }}
        uses: google-github-actions/auth@v3
        id: auth
        with:
          service_account: '${{ vars.GCP_SERVICE_ACCOUNT }}'
          workload_identity_provider: '${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          request_reason: ${{ github.workflow_ref }}

      - name: Upload to Google Play
        if: ${{ github.ref_name == 'main' }}
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ steps.auth.outputs.credentials_file_path }}
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          packageName: io.nv.subspacerelay.mobile
          releaseName: "${{ env.BUILD_NAME }}"
          tracks: internal
          status: draft

  build_ios:
    name: Build iOS
    runs-on: macos-latest
    timeout-minutes: 30
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.base.repo.full_name != github.event.pull_request.head.repo.full_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: stable
          cache: true

      - name: Fetch dependencies
        run: flutter pub get

      - name: Build iOS (no codesign)
        run: |
          flutter build ios --no-codesign --build-number="${{ github.run_number }}" --build-name="${{ env.BUILD_NAME }}"

      - name: Archive iOS build
        uses: actions/upload-artifact@v5
        with:
          name: "subspace_relay_mobile_ios_v${{ env.BUILD_NAME }}"
          path: build/ios/iphoneos/Runner.app
          if-no-files-found: error
